let catalog={tracks:[],folders:[]}, filtered=[], currentIndex=-1, repeatMode='off', deferredPrompt=null, displayLimit=80;
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const favKey='buddhadasa:favorites'; const lastKey='buddhadasa:last';
const favs=()=>new Set(JSON.parse(localStorage.getItem(favKey)||'[]')); const saveFavs=s=>localStorage.setItem(favKey,JSON.stringify([...s]));
function norm(s){return (s||'').toString().toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/\.mp3$/,'').trim()}
function trackUrl(t){return t.onedriveUrl}
function shareUrl(t){const u=new URL(location.href); u.searchParams.set('track',t.id); return u.toString()}
async function load(){try{catalog=await fetch('./audio-index.json',{cache:'no-store'}).then(r=>r.json())}catch(e){catalog={tracks:[],folders:[],error:String(e)}}; init()}
function init(){catalog.tracks=(catalog.tracks||[]).map((t,i)=>({...t,_i:i,search:norm([t.episode,t.title,t.fileName,t.album,t.category,t.path].join(' '))})); filtered=[...catalog.tracks]; $('#statTracks').textContent=catalog.tracks.length.toLocaleString('th-TH'); $('#statAlbums').textContent=new Set(catalog.tracks.map(t=>t.album)).size.toLocaleString('th-TH'); fillFilters(); renderChips(); bind(); applyFilters(); const id=new URL(location.href).searchParams.get('track'); if(id){const i=catalog.tracks.findIndex(t=>t.id===id); if(i>=0) selectTrack(i,false)}}
function fillFilters(){for(const a of [...new Set(catalog.tracks.map(t=>t.album).filter(Boolean))]) $('#albumFilter').insertAdjacentHTML('beforeend',`<option>${a}</option>`); for(const c of [...new Set(catalog.tracks.map(t=>t.category).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'th'))) $('#categoryFilter').insertAdjacentHTML('beforeend',`<option>${c}</option>`)}
function renderChips(){const cats=[...new Set(catalog.tracks.map(t=>t.category).filter(Boolean))].slice(0,24); $('#chips').innerHTML=cats.map(c=>`<button class="chip" data-cat="${escapeHtml(c)}">${escapeHtml(c)}</button>`).join('')}
function bind(){['input','change'].forEach(ev=>{$('#searchInput').addEventListener(ev,applyFilters);$('#albumFilter').addEventListener(ev,applyFilters);$('#categoryFilter').addEventListener(ev,applyFilters)}); $('#clearBtn').onclick=()=>{$('#searchInput').value='';$('#albumFilter').value='';$('#categoryFilter').value='';applyFilters()}; $('#shuffleBtn').onclick=shuffle; $('#randomHero').onclick=shuffle; $('#repeatBtn').onclick=()=>{repeatMode=repeatMode==='off'?'one':repeatMode==='one'?'all':'off'; $('#repeatBtn').dataset.mode=repeatMode; $('#repeatBtn').textContent='🔁 Repeat: '+repeatMode}; $('#shareAppBtn').onclick=()=>share({title:document.title,url:location.href}); $('#shareTrackBtn').onclick=()=>{const t=catalog.tracks[currentIndex]; if(t) share({title:t.title,text:t.category,url:shareUrl(t)})}; $('#openOneDrive').onclick=()=>{const t=catalog.tracks[currentIndex]; if(t) window.open(trackUrl(t),'_blank')}; $('#playBtn').onclick=()=>{const t=catalog.tracks[currentIndex]||filtered[0]; if(t) play(t)}; $('#prevBtn').onclick=()=>move(-1); $('#nextBtn').onclick=()=>move(1); $('#backBtn').onclick=()=>alert('OneDrive preview เป็น player ภายนอก จึงถอยเวลาในหน้าเราไม่ได้ ให้ใช้ปุ่มใน OneDrive player ค่ะ'); $('#forwardBtn').onclick=()=>alert('OneDrive preview เป็น player ภายนอก จึงเดินหน้าเวลาในหน้าเราไม่ได้ ให้ใช้ปุ่มใน OneDrive player ค่ะ'); $('#muteBtn').onclick=()=>alert('เสียงเล่นใน OneDrive preview ให้กด mute ในหน้าต่าง OneDrive ได้ค่ะ'); $$('.tab').forEach(b=>b.onclick=()=>showView(b.dataset.view)); $('#chips').onclick=e=>{const b=e.target.closest('.chip'); if(!b)return; $('#categoryFilter').value=b.dataset.cat; applyFilters()}; window.addEventListener('beforeinstallprompt',e=>{e.preventDefault(); deferredPrompt=e; $('#installBtn').style.display='inline-flex'}); $('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt(); deferredPrompt=null}else alert('บน iPhone: กด Share > Add to Home Screen\nบน Android: เมนู browser > Install app ค่ะ')}}
function applyFilters(){displayLimit=80; const q=norm($('#searchInput').value), a=$('#albumFilter').value, c=$('#categoryFilter').value; filtered=catalog.tracks.filter(t=>(!q||t.search.includes(q))&&(!a||t.album===a)&&(!c||t.category===c)); renderList(filtered,$('#trackList')); $('#resultCount').textContent=`พบ ${filtered.length.toLocaleString('th-TH')} ตอน`; renderFavs()}
function renderList(list, el){if(!list.length){el.innerHTML='<div class="track"><h3>ยังไม่พบรายการ</h3><p>ลองล้างตัวกรองหรือใช้คำค้นอื่นค่ะ</p></div>';return} const isMain=el.id==='trackList'; const visible=isMain?list.slice(0,displayLimit):list; el.innerHTML=visible.map(t=>card(t)).join('') + (isMain && list.length>displayLimit ? `<button class="load-more" onclick="displayLimit+=80;renderList(filtered,document.querySelector('#trackList'))">โหลดเพิ่มอีก ${Math.min(80,list.length-displayLimit).toLocaleString('th-TH')} รายการ</button>` : '')}
function card(t){const f=favs().has(t.id); return `<article class="track"><div class="track-top"><div class="num">${escapeHtml(t.episode||'ธรรม')}</div><div><h3>${escapeHtml(t.title||t.fileName)}</h3><p>${escapeHtml(t.album)} • ${escapeHtml(t.category)}</p><p>${escapeHtml(t.size||'')} ${t.modified? '• '+escapeHtml(t.modified):''}</p></div></div><div class="track-actions"><button class="play" onclick="selectTrack(${t._i},true)">▶ ฟัง</button><button onclick="toggleFav('${t.id}')">${f?'♥':'♡'} โปรด</button><button onclick="shareTrack('${t.id}')">📤 แชร์</button><a href="${trackUrl(t)}" target="_blank" rel="noopener">OneDrive</a></div></article>`}
function selectTrack(i,autoplay){currentIndex=i; const t=catalog.tracks[i]; localStorage.setItem(lastKey,t.id); $('#nowTitle').textContent=(t.episode? t.episode+' ':'')+t.title; $('#nowMeta').textContent=t.album+' • '+t.category; if(autoplay) play(t)}
function play(t){selectTrack(t._i,false); window.open(trackUrl(t),'_blank','noopener')}
function move(d){if(!filtered.length)return; const cur=filtered.findIndex(t=>t._i===currentIndex); let ni=cur<0?0:cur+d; if(ni<0)ni=repeatMode==='all'?filtered.length-1:0; if(ni>=filtered.length)ni=repeatMode==='all'?0:filtered.length-1; selectTrack(filtered[ni]._i,true)}
function shuffle(){if(!filtered.length)return; const t=filtered[Math.floor(Math.random()*filtered.length)]; selectTrack(t._i,true)}
window.toggleFav=id=>{const s=favs(); s.has(id)?s.delete(id):s.add(id); saveFavs(s); applyFilters()}; function renderFavs(){const s=favs(); renderList(catalog.tracks.filter(t=>s.has(t.id)),$('#favoriteList'))}
window.shareTrack=id=>{const t=catalog.tracks.find(x=>x.id===id); if(t) share({title:t.title,text:t.category,url:shareUrl(t)})}; async function share(data){if(navigator.share) await navigator.share(data).catch(()=>{}); else {await navigator.clipboard.writeText(data.url); alert('คัดลอกลิงก์แล้วค่ะ')}}
function showView(id){$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===id)); $$('.view').forEach(v=>v.classList.toggle('active',v.id===id))}
function escapeHtml(s){return (s??'').toString().replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(()=>{}); load();